### ISSUE TITLE
Arrow visibility

### ISSUE THREAD

**Issue by Minighost** [CombustibleToast/StratagemHeroOnline#17]
The arrows are really hard to see for certain people. We would appreciate it if there was some sort of light mode option (or an option to make the arrows start white and inputs make them yellow, like in the game). Otherwise, very solid sim, looking forward to future updates!

**Comment by CombustibleToast** [comment]
Great issue, thank you for bringing it up. Will look into solutions now

**Comment by CombustibleToast** [comment]
Alright it should be much more visible now, but github is not updating the arrow icons to be yellow. Hopefully they will show up soon

**Comment by CombustibleToast** [comment]
![image](https://github.com/CombustibleToast/StratagemHeroOnline/assets/34487106/a3b22b0b-dc0b-4226-b3ac-d1a5a9c2b915)
Here's what it should look like

**Comment by CombustibleToast** [comment]
oh seems like it's up!

**Comment by Minighost** [comment]
I just saw the change. Thanks, it looks great!
