### ISSUE TITLE
Incorrect Stratagem Inputs

### ISSUE THREAD

**Issue by Brink415** [CombustibleToast/StratagemHeroOnline#21]
The current shield generator pack is presented as:
Shield Generator Pack: 🡇🡇🡄🡆🡄🡆

It should be: 🡇🡅🡄🡆🡄🡆

**Comment by CombustibleToast** [comment]
Should be fixed, thanks!

**Comment by SavageCore** [comment]
This was actually my bad, latest PR fixes it.

Shield Generator Pack was listed twice when one of them is actually Shield Generator Relay.

My Userscript to export from [the guide](https://steamcommunity.com/sharedfiles/filedetails/?id=3161075951) was [wrong](https://github.com/SavageCore/stratagem-export/commit/3e4f22f5af49e2906e83496c928dcea89aeddcd5)
