### ISSUE TITLE
Contribution with adding keybindings edit.

### ISSUE THREAD

**Issue by Alexander-ilyin3** [CombustibleToast/StratagemHeroOnline#22]
Hello. 
I want to contribute to the project. Namely, to add key reassignment for the keyboard. This option is available in the game. 

I have never contributed to other projects before. I have experience in js and all that, but I couldn't run the game locally :). 
I see "HI :) You shouldn't see this"

I see that you are not using npm and libraries like react or vue. As far as I know, when you run the html, the script.js that is written in it should load. But this is not happening.

Maybe you're using one of the github workflows (which I've never done either)?

So, give me a hint, what tools do you use to start and develop the project locally?

**Comment by CombustibleToast** [comment]
Hi, thanks for the interest! In the previous iteration of this game, you were able to just open index.html in your browser and it worked (this is still the case with Old/index.html). 

Now, however, you need to locally host the file. I do this with the VSCode extension [Live Server[(https://marketplace.visualstudio.com/items?itemName=ritwickdey.LiveServer). Once I have the repo open in VSCode I can just click "Go Live" in the bottom bar and it opens up a locally hosted page for index.html.

**Comment by Alexander-ilyin3** [comment]
Thanks for quick responce!
