### ISSUE TITLE
Arrows display as unknown characters on mobile

### ISSUE THREAD

**Issue by TexZeTech** [CombustibleToast/StratagemHeroOnline#26]
The font that is being used doesn't seem to work well on Androids system.
I have not confirmed on Iphone.

From Firefox mobile (android)
<img width="322" alt="Screenshot_20240317_105359" src="https://github.com/CombustibleToast/StratagemHeroOnline/assets/7254540/a90ebafd-b7bb-4235-ae1e-9a1b1b38dea6">

From Google Chrome (android)
<img width="322" alt="Screenshot_20240317_105528" src="https://github.com/CombustibleToast/StratagemHeroOnline/assets/7254540/ddb436ad-be50-48ca-a8af-5c270c8557ce">

Shared directly from desktop Signal to Signal on Android.
<img width="322" alt="Screenshot_20240317_110213" src="https://github.com/CombustibleToast/StratagemHeroOnline/assets/7254540/aa1d9ed5-3bf6-4d99-9949-2488f0ae5660">

**Comment by malachaifrazier** [comment]
I'm seeing this, too. Is this a missing character thing? Looks like it comes from [here in the code](https://github.com/CombustibleToast/StratagemHeroOnline/blob/3b1d09cd84e9918412f5ed798d6088624b7a36df/script.js#L333):

**Comment by TexZeTech** [comment]
> I'm seeing this, too. Is this a missing character thing? I think they're supposed to be emojis... Looks like it comes from [here in the code](https://github.com/CombustibleToast/StratagemHeroOnline/blob/3b1d09cd84e9918412f5ed798d6088624b7a36df/script.js#L333):

Try viewing it raw. 
![image](https://github.com/CombustibleToast/StratagemHeroOnline/assets/7254540/0bc6ee82-2057-4616-99a1-a30f07b0fd50)

I definitely think its a language pack that isn't on my android phone at the very least.

**Comment by CombustibleToast** [comment]
Yeah, mobile doesn't support those characters for some reason. I'll make a fix really quick

**Comment by CombustibleToast** [comment]
Addressed in b6febc4, though copying from desktop to mobile will still cause issues. I definitely prefer having the unicode characters as most people will be playing on desktop.
