### ISSUE TITLE
Feature Request: Please add a mode for Helldivers 2

### ISSUE THREAD

**Issue by mavanmanen** [CombustibleToast/StratagemHeroOnline#3]
Would be nice if there there was a version that had all the HD2 stratagems so I can get to practicing them 😄

**Comment by CombustibleToast** [comment]
This is coming soon after there's a list of stratagems, their images, and their input sequences!

**Comment by SavageCore** [comment]
This is the most complete list I have found, with just 3 icons missing: https://steamcommunity.com/sharedfiles/filedetails/?id=3161075951

[stratagems.json](https://github.com/CombustibleToast/StratagemHeroOnline/files/14324954/stratagems.json)

**Comment by CombustibleToast** [comment]
Oh sweet, thanks for the JSON too

**Comment by CombustibleToast** [comment]
This is now being worked on in the hd2 branch

**Comment by SavageCore** [comment]
Oh, one correction so far, they had `HMG Placement` it's `HMG Emplacement`

Finally got in-game again!

**Comment by CombustibleToast** [comment]
It's up!
