### ISSUE TITLE
Add Emancipator Exosuit

### ISSUE THREAD

**Issue by Floating-Toilet** [CombustibleToast/StratagemHeroOnline#37]
{
    "name": "Emancipator Exosuit",
    "sequence": "LDRULDU",
    "image": "Emancipator_Exosuit.svg"
  }

just add image and copy & paste into HD2-Sequences.json

**Comment by CombustibleToast** [comment]
Will do! Thanks!

There are quite a few stratagems that need to be added, will get around to adding all of them soon
